MapManager and MapManagerTest plus a subTestProject
Damiano101/MartyAdventure pull request #12
Opened 2021-05-12 14:57 UTC by ste-script

2021-05-13 16:20 UTC, Mek101 commented
3790745e094c2871a70d25be6cf4fcfa404101b2 è un "feature: add..."

2021-05-13 16:24 UTC, Mek101 commented
`desktop/.project` viene rimosso dal progetto, ma deve rimanere, solo col percorso relativo

2021-05-14 07:32 UTC, Damiano101 commented on desktop/.project
>  		<link>
Questo file va tolto

2021-05-14 07:32 UTC, Damiano101 commented on test/bin/.gitignore
> +/main/
./bin non dovbrebbe nemmeno esserci

2021-05-14 07:32 UTC, Damiano101 commented on build.gradle
> +project(":test") {
Il nuovo progetto da dove viene? È qui perché è stato aggiunto da eclipse?

2021-05-14 07:32 UTC, Damiano101 commented on build.gradle
> +        	testCompileOnly 'junit:junit:4.12'
Stiamo usando Junit 5

2021-05-14 07:32 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/Toolbox.java
> +        Toolbox.assetManager.setLoader(TiledMap.class, new TmxMapLoader());
Da quel che vedo questo metodo qui servirebbe solo se stiamo definendo dei loader custom, e visto che `TmxMapLoader` fa parte di libGDx, non dovrebbe servire

2021-05-14 07:32 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/Toolbox.java
> +        Toolbox.assetManager.finishLoadingAsset(mapPath);
Questo metodo è bloccante, non avrebbe senso usarlo quando gli asset vengono gradualmente caricati con delle call ad `updateAssetLoading()`

2021-05-14 07:32 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/Toolbox.java
> +        Toolbox.assetManager.finishLoadingAsset(mapPath);
Nvm, lo sistemo io con la prossima PR

2021-05-14 07:37 UTC, Damiano101 requested changes

2021-05-14 07:37 UTC, Damiano101 commented on settings.gradle
> +include 'desktop', 'core', 'test'
`test` va tolto siccome non è un progetto a sé stante

2021-05-14 07:37 UTC, Damiano101 commented on desktop/src/edu/unibo/martyadventure/desktop/DesktopLauncher.java
> +        Gdx.app = app;
Non servono queste modifiche, lo fa già il costruttore di Lwjgl3Application: https://github.com/libgdx/libgdx/blob/36fd9b3f84990ae4affbaef8e1021a38c2cf864c/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java#L95

2021-05-17 19:07 UTC, Mek101 requested changes

2021-05-17 19:07 UTC, Mek101 commented on core/src/edu/unibo/martyadventure/view/MapManager.java
> +    private static final String MAP1 = "map1";
La convenzione Java vorrebbe gli underscore per spezzare le parole

2021-05-17 19:07 UTC, Mek101 commented on core/src/edu/unibo/martyadventure/model/weapon/Move.java
> -    HOOK("Gancio", 5, 10, 2, 'M', 0), SHOOT("Lancio", 5, 10, 2, 'R', 0), JAB("Diretto", 60, 15, 3, 'M', 0);
Questo deve rimanere 60 come l'ha impostato bomba oggi

2021-05-17 19:07 UTC, Mek101 commented on core/tests/test/edu/unibo/martyadventure/view/TestMapManager.java
> +    String map1 = "map1";
Questi field String vanno private

2021-05-17 19:07 UTC, Mek101 commented on core/tests/test/edu/unibo/martyadventure/view/TestMapManager.java
> +    MapManager manager = new MapManager();
Idem

2021-05-18 09:16 UTC, ste-script commented on core/src/edu/unibo/martyadventure/view/MapManager.java
> +    private static final String MAP1 = "map1";
sistemato

2021-05-18 09:16 UTC, ste-script commented on core/src/edu/unibo/martyadventure/model/weapon/Move.java
> -    HOOK("Gancio", 5, 10, 2, 'M', 0), SHOOT("Lancio", 5, 10, 2, 'R', 0), JAB("Diretto", 60, 15, 3, 'M', 0);
ho fatto il fetch delle modifiche di bomba

2021-05-18 09:18 UTC, ste-script commented on core/tests/test/edu/unibo/martyadventure/view/TestMapManager.java
> +    MapManager manager = new MapManager();
fixato

2021-05-18 12:21 UTC, Damiano101 requested changes

2021-05-18 12:21 UTC, Damiano101 commented on core/tests/test/edu/unibo/martyadventure/view/TestMapManager.java
> +    void TestLoadingLayers(String mapName) {
Questa funzione non serve più, toglila

2021-05-18 12:21 UTC, Damiano101 commented on core/tests/test/edu/unibo/martyadventure/view/TestMapManager.java
> +    void TestLoadingMap(String mapName) {
Questo test non verrà mai chiamato

2021-05-19 08:04 UTC, merged