Feature add player choice, sound, weapon choice, enemy change, combat screeen, menu screen
Damiano101/MartyAdventure pull request #29
Opened 2021-06-18 16:15 UTC by ste-script

2021-06-18 21:00 UTC, Damiano101 requested changes

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/MartyAdventureGame.java
>      public void dispose() {
Se non ci deve star niente (e sei sicuro che non ci deva star niente?) toglilo

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/model/character/Character.java
> +     * pubblic constructor
Una 'b' di troppo

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/model/fight/Fight.java
> +        mapMartyMove = new HashMap<>();
Avrei fatto una funzione, ma amen

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/model/fight/Fight.java
> +        if (isMoveUsable(player, inputMove))
Mancano le graffe

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/model/fight/Fight.java
>       * Check if the damage will kill the character
Non è chiarissimo che si riferisce all'avversario, ma amen

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/model/fight/Fight.java
> +    public Character fightWinner() {
Un semplice hasPlayerWon() qui visto che ritorna o l'oggetto player o null comunque?

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/model/weapon/Move.java
> +    HOOK("Gancio", 5, 10, 0, 'M'),
Sarebbe meglio usare delle costanti o una enum al posto di due caratteri, ma è più una questione per @LorenzoBombardini

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/model/weapon/WeaponFactory.java
>          int i = 0;
Qua si può usare direttamente la size invece di un contatore esterno, ma anche qui @LorenzoBombardini

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/MovementGameScreen.java
> +        enemyList.forEach(e -> e.setDirection(Arrays.asList(EntityDirection.values()).get(new Random().nextInt(3))));
Reinizializza il random tutte le volte da 0, probabilissimo che ti esca tutte le volte lo stesso numero

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/MovementGameScreen.java
> +        } else {
Questo è più il lavoro di uno switch, ma amen

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/character/CharacterViewFactory.java
> +        martyTextureMapPath = new HashMap<>();
Invece di fare mille mila HashMap, fare un Enum map con una classe privata contenente tutti i dati per ogni livello?

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/character/CharacterViewFactory.java
> +                new Random().nextBoolean() ? ENEMY_PATH_1 : ENEMY_PATH_2, b, weaponView, dropWeaponView);
Stesso problema dell'altro random

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/character/EnemyCharacterView.java
> +        super(initialPosition, 20f, 5f, 70f, new TextureRegion(new Texture(enemy_path)), FRAME_WIDTH, FRAME_HEIGHT, weapon);
Quei 3 numeri li cosa sono?

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/weapon/WeaponViewFactory.java
> +        return Weapons.values()[(int) (Math.random() * Weapons.values().length)];
Qui si può tranquillamente usare il ThreadLocalRandom

2021-06-18 21:00 UTC, Damiano101 commented on core/src/edu/unibo/martyadventure/view/weapon/WeaponViewFactory.java
> +        return Weapons.values()[(int) (Math.random() * Weapons.values().length)];
Bella classe per il resto

2021-06-18 21:00 UTC, Damiano101 commented on desktop/src/edu/unibo/martyadventure/desktop/DesktopLauncher.java
> +        config.setWindowSizeLimits(600, 338, 5120, 2880);
Da dove li hai pescati questi limiti?

2021-06-20 13:24 UTC, LorenzoBombardini commented on core/src/edu/unibo/martyadventure/model/fight/Fight.java
>       * Check if the damage will kill the character
Che cosa? La funzione?

2021-06-20 13:27 UTC, LorenzoBombardini commented on core/src/edu/unibo/martyadventure/model/fight/Fight.java
> +    public Character fightWinner() {
Cioè cambiare solo il nome?

2021-06-20 15:11 UTC, Damiano101 commented
Buono così. Mergio, poi ci applico la mia PR

2021-06-20 15:15 UTC, merged